import type { Locale } from '../../prefs'

/**
 * Paires de mots pour Undercover : [mot des civils, mot de l'undercover].
 * Les deux mots doivent être proches mais distinguables par une description fine.
 * Une liste par langue : traduire les paires une à une donnerait des couples
 * bancals (« Belote » n'a pas d'équivalent anglais évident).
 */
type WordPair = readonly [string, string]

const FR: WordPair[] = [
  ['Chat', 'Chien'],
  ['Café', 'Thé'],
  ['Pizza', 'Quiche'],
  ['Plage', 'Piscine'],
  ['Guitare', 'Ukulélé'],
  ['Avion', 'Hélicoptère'],
  ['Train', 'Métro'],
  ['Vélo', 'Trottinette'],
  ['Beurre', 'Margarine'],
  ['Crêpe', 'Gaufre'],
  ['Vin', 'Bière'],
  ['Neige', 'Pluie'],
  ['Montagne', 'Colline'],
  ['Docteur', 'Infirmier'],
  ['Professeur', 'Formateur'],
  ['Police', 'Gendarmerie'],
  ['Roman', 'Bande dessinée'],
  ['Cinéma', 'Théâtre'],
  ['Netflix', 'YouTube'],
  ['Football', 'Rugby'],
  ['Tennis', 'Badminton'],
  ['Piano', 'Orgue'],
  ['Boulangerie', 'Pâtisserie'],
  ['Croissant', 'Pain au chocolat'],
  ['Fromage', 'Yaourt'],
  ['Sushi', 'Maki'],
  ['Burger', 'Sandwich'],
  ['Frites', 'Chips'],
  ['Chocolat', 'Caramel'],
  ['Glace', 'Sorbet'],
  ['Miel', 'Confiture'],
  ['Citron', 'Orange'],
  ['Pomme', 'Poire'],
  ['Fraise', 'Framboise'],
  ['Pastèque', 'Melon'],
  ['Tomate', 'Poivron'],
  ['Carotte', 'Navet'],
  ['Riz', 'Semoule'],
  ['Pâtes', 'Nouilles'],
  ['Soupe', 'Bouillon'],
  ['Couteau', 'Ciseaux'],
  ['Fourchette', 'Cuillère'],
  ['Assiette', 'Plateau'],
  ['Verre', 'Tasse'],
  ['Bouteille', 'Gourde'],
  ['Casserole', 'Poêle'],
  ['Four', 'Micro-ondes'],
  ['Frigo', 'Congélateur'],
  ['Balai', 'Aspirateur'],
  ['Douche', 'Baignoire'],
  ['Savon', 'Shampoing'],
  ['Serviette', 'Peignoir'],
  ['Brosse à dents', 'Peigne'],
  ['Miroir', 'Fenêtre'],
  ['Rideau', 'Store'],
  ['Canapé', 'Fauteuil'],
  ['Lit', 'Hamac'],
  ['Oreiller', 'Couverture'],
  ['Bougie', 'Lampe'],
  ['Horloge', 'Montre'],
  ['Téléphone', 'Tablette'],
  ['Ordinateur', 'Console'],
  ['Casque', 'Écouteurs'],
  ['Appareil photo', 'Caméra'],
  ['Clé USB', 'Disque dur'],
  ['Imprimante', 'Photocopieuse'],
  ['Stylo', 'Crayon'],
  ['Cahier', 'Agenda'],
  ['Gomme', 'Correcteur'],
  ['Sac à dos', 'Valise'],
  ['Portefeuille', 'Trousse'],
  ['Parapluie', 'Casquette'],
  ['Écharpe', 'Foulard'],
  ['Gant', 'Moufle'],
  ['Chaussure', 'Chausson'],
  ['Basket', 'Sandale'],
  ['Jean', 'Pantalon'],
  ['Robe', 'Jupe'],
  ['Pull', 'Gilet'],
  ['Manteau', 'Doudoune'],
  ['Chemise', 'Tee-shirt'],
  ['Bague', 'Bracelet'],
  ['Collier', 'Chaîne'],
  ['Lunettes', 'Loupe'],
  ['Voiture', 'Camion'],
  ['Moto', 'Scooter'],
  ['Bateau', 'Sous-marin'],
  ['Fusée', 'Satellite'],
  ['Route', 'Autoroute'],
  ['Pont', 'Tunnel'],
  ['Hôtel', 'Auberge'],
  ['Camping', 'Chalet'],
  ['Musée', 'Galerie'],
  ['Bibliothèque', 'Librairie'],
  ['Supermarché', 'Épicerie'],
  ['Marché', 'Brocante'],
  ['Hôpital', 'Clinique'],
  ['Pharmacie', 'Parapharmacie'],
  ['École', 'Université'],
  ['Bureau', 'Atelier'],
  ['Usine', 'Entrepôt'],
  ['Ferme', 'Zoo'],
  ['Jardin', 'Parc'],
  ['Forêt', 'Jungle'],
  ['Désert', 'Savane'],
  ['Rivière', 'Fleuve'],
  ['Lac', 'Étang'],
  ['Océan', 'Mer'],
  ['Île', 'Presqu’île'],
  ['Volcan', 'Geyser'],
  ['Étoile', 'Planète'],
  ['Soleil', 'Lune'],
  ['Nuage', 'Brouillard'],
  ['Orage', 'Tempête'],
  ['Vent', 'Brise'],
  ['Feu', 'Braise'],
  ['Sable', 'Terre'],
  ['Pierre', 'Brique'],
  ['Or', 'Argent'],
  ['Diamant', 'Cristal'],
  ['Papier', 'Carton'],
  ['Corde', 'Fil'],
  ['Marteau', 'Massue'],
  ['Clou', 'Vis'],
  ['Échelle', 'Escalier'],
  ['Ascenseur', 'Escalator'],
  ['Porte', 'Portail'],
  ['Clé', 'Badge'],
  ['Serrure', 'Cadenas'],
  ['Boxe', 'Karaté'],
  ['Course', 'Marche'],
  ['Natation', 'Plongée'],
  ['Ski', 'Snowboard'],
  ['Surf', 'Kitesurf'],
  ['Escalade', 'Randonnée'],
  ['Cheval', 'Âne'],
  ['Vache', 'Chèvre'],
  ['Mouton', 'Lama'],
  ['Poule', 'Canard'],
  ['Lion', 'Tigre'],
  ['Loup', 'Renard'],
  ['Ours', 'Panda'],
  ['Singe', 'Gorille'],
  ['Éléphant', 'Rhinocéros'],
  ['Girafe', 'Autruche'],
  ['Dauphin', 'Requin'],
  ['Poisson', 'Crevette'],
  ['Abeille', 'Guêpe'],
  ['Papillon', 'Libellule'],
  ['Araignée', 'Scorpion'],
  ['Serpent', 'Lézard'],
  ['Tortue', 'Escargot'],
  ['Pingouin', 'Phoque'],
  ['Aigle', 'Faucon'],
  ['Pigeon', 'Mouette'],
  ['Anniversaire', 'Mariage'],
  ['Noël', 'Nouvel An'],
  ['Vacances', 'Week-end'],
  ['Fête', 'Concert'],
  ['Photo', 'Selfie'],
  ['Rêve', 'Cauchemar'],
  ['Sieste', 'Nuit'],
  ['Sourire', 'Rire'],
  ['Câlin', 'Bisou'],
  ['Secret', 'Mensonge'],
  ['Peur', 'Stress'],
  ['Colère', 'Jalousie'],
  ['Roi', 'Président'],
  ['Chevalier', 'Samouraï'],
  ['Pirate', 'Corsaire'],
  ['Sorcier', 'Magicien'],
  ['Fantôme', 'Zombie'],
  ['Vampire', 'Loup-garou'],
  ['Robot', 'Cyborg'],
  ['Super-héros', 'Ninja'],
  ['Détective', 'Espion'],
  ['Pompier', 'Secouriste'],
  ['Chef cuisinier', 'Serveur'],
  ['Facteur', 'Livreur'],
  ['Coiffeur', 'Barbier'],
  ['Dentiste', 'Orthodontiste'],
  ['Avocat', 'Juge'],
  ['Journaliste', 'Écrivain'],
  ['Chanteur', 'Rappeur'],
  ['Acteur', 'Mannequin'],
  ['Peintre', 'Sculpteur'],
  ['Danseur', 'Gymnaste'],
  ['Pilote', 'Chauffeur'],
  ['Astronaute', 'Explorateur'],
  ['Boussole', 'Carte'],
  ['Trésor', 'Cadeau'],
  ['Tatouage', 'Cicatrice'],
  ['Barbe', 'Moustache'],
  ['Selfie stick', 'Trépied'],
  ['Karaoké', 'Blind test'],
  ['Échecs', 'Dames'],
  ['Poker', 'Belote'],
  ['Puzzle', 'Mots croisés'],
  ['Loterie', 'Tombola'],
]

const EN: WordPair[] = [
  ['Cat', 'Dog'],
  ['Coffee', 'Tea'],
  ['Pizza', 'Quiche'],
  ['Beach', 'Swimming pool'],
  ['Guitar', 'Ukulele'],
  ['Plane', 'Helicopter'],
  ['Train', 'Underground'],
  ['Bicycle', 'Scooter'],
  ['Butter', 'Margarine'],
  ['Pancake', 'Waffle'],
  ['Wine', 'Beer'],
  ['Snow', 'Rain'],
  ['Mountain', 'Hill'],
  ['Doctor', 'Nurse'],
  ['Teacher', 'Coach'],
  ['Police', 'Army'],
  ['Novel', 'Comic book'],
  ['Cinema', 'Theatre'],
  ['Netflix', 'YouTube'],
  ['Football', 'Rugby'],
  ['Tennis', 'Badminton'],
  ['Piano', 'Organ'],
  ['Bakery', 'Patisserie'],
  ['Croissant', 'Doughnut'],
  ['Cheese', 'Yoghurt'],
  ['Sushi', 'Maki'],
  ['Burger', 'Sandwich'],
  ['Chips', 'Crisps'],
  ['Chocolate', 'Caramel'],
  ['Ice cream', 'Sorbet'],
  ['Honey', 'Jam'],
  ['Lemon', 'Orange'],
  ['Apple', 'Pear'],
  ['Strawberry', 'Raspberry'],
  ['Watermelon', 'Melon'],
  ['Tomato', 'Pepper'],
  ['Carrot', 'Turnip'],
  ['Rice', 'Couscous'],
  ['Pasta', 'Noodles'],
  ['Soup', 'Broth'],
  ['Knife', 'Scissors'],
  ['Fork', 'Spoon'],
  ['Plate', 'Tray'],
  ['Glass', 'Mug'],
  ['Bottle', 'Flask'],
  ['Saucepan', 'Frying pan'],
  ['Oven', 'Microwave'],
  ['Fridge', 'Freezer'],
  ['Broom', 'Vacuum cleaner'],
  ['Shower', 'Bathtub'],
  ['Soap', 'Shampoo'],
  ['Towel', 'Bathrobe'],
  ['Toothbrush', 'Comb'],
  ['Mirror', 'Window'],
  ['Curtain', 'Blind'],
  ['Sofa', 'Armchair'],
  ['Bed', 'Hammock'],
  ['Pillow', 'Blanket'],
  ['Candle', 'Lamp'],
  ['Clock', 'Watch'],
  ['Phone', 'Tablet'],
  ['Computer', 'Console'],
  ['Headphones', 'Earbuds'],
  ['Camera', 'Camcorder'],
  ['USB stick', 'Hard drive'],
  ['Printer', 'Photocopier'],
  ['Pen', 'Pencil'],
  ['Notebook', 'Diary'],
  ['Eraser', 'Correction fluid'],
  ['Backpack', 'Suitcase'],
  ['Wallet', 'Pencil case'],
  ['Umbrella', 'Cap'],
  ['Scarf', 'Bandana'],
  ['Glove', 'Mitten'],
  ['Shoe', 'Slipper'],
  ['Trainer', 'Sandal'],
  ['Jeans', 'Trousers'],
  ['Dress', 'Skirt'],
  ['Jumper', 'Cardigan'],
  ['Coat', 'Puffer jacket'],
  ['Shirt', 'T-shirt'],
  ['Ring', 'Bracelet'],
  ['Necklace', 'Chain'],
  ['Glasses', 'Magnifying glass'],
  ['Car', 'Lorry'],
  ['Motorbike', 'Moped'],
  ['Boat', 'Submarine'],
  ['Rocket', 'Satellite'],
  ['Road', 'Motorway'],
  ['Bridge', 'Tunnel'],
  ['Hotel', 'Hostel'],
  ['Campsite', 'Cabin'],
  ['Museum', 'Gallery'],
  ['Library', 'Bookshop'],
  ['Supermarket', 'Corner shop'],
  ['Market', 'Car boot sale'],
  ['Hospital', 'Clinic'],
  ['Pharmacy', 'Drugstore'],
  ['School', 'University'],
  ['Office', 'Workshop'],
  ['Factory', 'Warehouse'],
  ['Farm', 'Zoo'],
  ['Garden', 'Park'],
  ['Forest', 'Jungle'],
  ['Desert', 'Savannah'],
  ['Stream', 'River'],
  ['Lake', 'Pond'],
  ['Ocean', 'Sea'],
  ['Island', 'Peninsula'],
  ['Volcano', 'Geyser'],
  ['Star', 'Planet'],
  ['Sun', 'Moon'],
  ['Cloud', 'Fog'],
  ['Thunderstorm', 'Hurricane'],
  ['Wind', 'Breeze'],
  ['Fire', 'Ember'],
  ['Sand', 'Soil'],
  ['Stone', 'Brick'],
  ['Gold', 'Silver'],
  ['Diamond', 'Crystal'],
  ['Paper', 'Cardboard'],
  ['Rope', 'Thread'],
  ['Hammer', 'Club'],
  ['Nail', 'Screw'],
  ['Ladder', 'Staircase'],
  ['Lift', 'Escalator'],
  ['Door', 'Gate'],
  ['Key', 'Badge'],
  ['Lock', 'Padlock'],
  ['Boxing', 'Karate'],
  ['Running', 'Walking'],
  ['Swimming', 'Diving'],
  ['Skiing', 'Snowboarding'],
  ['Surfing', 'Kitesurfing'],
  ['Climbing', 'Hiking'],
  ['Horse', 'Donkey'],
  ['Cow', 'Goat'],
  ['Sheep', 'Llama'],
  ['Hen', 'Duck'],
  ['Lion', 'Tiger'],
  ['Wolf', 'Fox'],
  ['Bear', 'Panda'],
  ['Monkey', 'Gorilla'],
  ['Elephant', 'Rhinoceros'],
  ['Giraffe', 'Ostrich'],
  ['Dolphin', 'Shark'],
  ['Fish', 'Prawn'],
  ['Bee', 'Wasp'],
  ['Butterfly', 'Dragonfly'],
  ['Spider', 'Scorpion'],
  ['Snake', 'Lizard'],
  ['Turtle', 'Snail'],
  ['Penguin', 'Seal'],
  ['Eagle', 'Falcon'],
  ['Pigeon', 'Seagull'],
  ['Birthday', 'Wedding'],
  ['Christmas', 'New Year'],
  ['Holiday', 'Weekend'],
  ['Party', 'Concert'],
  ['Photo', 'Selfie'],
  ['Dream', 'Nightmare'],
  ['Nap', 'Night'],
  ['Smile', 'Laugh'],
  ['Hug', 'Kiss'],
  ['Secret', 'Lie'],
  ['Fear', 'Stress'],
  ['Anger', 'Jealousy'],
  ['King', 'President'],
  ['Knight', 'Samurai'],
  ['Pirate', 'Privateer'],
  ['Wizard', 'Magician'],
  ['Ghost', 'Zombie'],
  ['Vampire', 'Werewolf'],
  ['Robot', 'Cyborg'],
  ['Superhero', 'Ninja'],
  ['Detective', 'Spy'],
  ['Firefighter', 'Paramedic'],
  ['Chef', 'Waiter'],
  ['Postman', 'Courier'],
  ['Hairdresser', 'Barber'],
  ['Dentist', 'Orthodontist'],
  ['Lawyer', 'Judge'],
  ['Journalist', 'Writer'],
  ['Singer', 'Rapper'],
  ['Actor', 'Model'],
  ['Painter', 'Sculptor'],
  ['Dancer', 'Gymnast'],
  ['Pilot', 'Driver'],
  ['Astronaut', 'Explorer'],
  ['Compass', 'Map'],
  ['Treasure', 'Present'],
  ['Tattoo', 'Scar'],
  ['Beard', 'Moustache'],
  ['Selfie stick', 'Tripod'],
  ['Karaoke', 'Quiz night'],
  ['Chess', 'Draughts'],
  ['Poker', 'Bridge'],
  ['Jigsaw', 'Crossword'],
  ['Lottery', 'Raffle'],
]

export const WORD_PAIRS: Record<Locale, WordPair[]> = { fr: FR, en: EN }
